apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: infrabin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: infrabin
spec:
  hosts:
  - "*"
  gateways:
  - infrabin-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: infrabin.infrabin.svc.cluster.local 
