apiVersion: v1
kind: Service
metadata:
  namespace: infrabin
  labels:
    app: infrabin
    service: infrabin
  name: infrabin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8080
  selector:
    app: infrabin